<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="36015" started-at="2018-01-03T10:53:42Z" finished-at="2018-01-03T10:54:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="36015" started-at="2018-01-03T10:53:42Z" finished-at="2018-01-03T10:54:18Z">
      <class name="TestCases.TestSuite">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestCases.TestSuite@2a742aa2]" name="setUp" is-config="true" duration-ms="18216" started-at="2018-01-03T16:23:42Z" finished-at="2018-01-03T16:24:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="VerifyPage()[pri:1, instance:TestCases.TestSuite@2a742aa2]" name="VerifyPage" duration-ms="2880" started-at="2018-01-03T16:24:00Z" finished-at="2018-01-03T16:24:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Wrong Page]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Wrong Pageat org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)at TestCases.LoginTestCase.abcd(LoginTestCase.java:57)at TestCases.TestSuite.VerifyPage(TestSuite.java:62)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyPage -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestCases.TestSuite@2a742aa2]" name="getResult" is-config="true" duration-ms="769" started-at="2018-01-03T16:24:03Z" finished-at="2018-01-03T16:24:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=VerifyPage status=FAILURE method=TestSuite.VerifyPage()[pri:1, instance:TestCases.TestSuite@2a742aa2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="FAIL" signature="LoginFunctionality()[pri:2, instance:TestCases.TestSuite@2a742aa2]" name="LoginFunctionality" duration-ms="6176" started-at="2018-01-03T16:24:03Z" finished-at="2018-01-03T16:24:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail : Login Functionality -> Should display user name as :- SAND page url:- http://web1.anasource.com/RMSUATInternal/UserPages/RouteDetails.aspx]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail : Login Functionality -> Should display user name as :- SAND page url:- http://web1.anasource.com/RMSUATInternal/UserPages/RouteDetails.aspxat org.testng.AssertJUnit.fail(AssertJUnit.java:59)at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)at TestCases.LoginTestCase.def(LoginTestCase.java:100)at TestCases.TestSuite.LoginFunctionality(TestSuite.java:68)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginFunctionality -->
        <test-method status="PASS" signature="getResult(org.testng.ITestResult)[pri:0, instance:TestCases.TestSuite@2a742aa2]" name="getResult" is-config="true" duration-ms="428" started-at="2018-01-03T16:24:10Z" finished-at="2018-01-03T16:24:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginFunctionality status=FAILURE method=TestSuite.LoginFunctionality()[pri:2, instance:TestCases.TestSuite@2a742aa2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestCases.TestSuite@2a742aa2]" name="tearDown" is-config="true" duration-ms="7527" started-at="2018-01-03T16:24:10Z" finished-at="2018-01-03T16:24:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.TestSuite -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
